- name: Ensure valid action
  assert:
    that:
      - action is defined
      - action in role_actions
  tags:
  - always

- name: "Call {{action}} action"
  include_tasks:
    file: "{{action}}.yml"
  tags:
  - always
